project:
  type: website

website:
  title: "VM0048"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer:
    left: "[Source](https://github.com/seamusrobertmurphy/VM0048)"
  navbar:
    title: "VM0048"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Baseline"
        href: baseline.qmd
      - text: "Risk"
        href: deforisk.qmd
      - text: "Leakage"
        href: leakage.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/seamusrobertmurphy/VM0048
          - text: Report a Bug
            href: https://github.com/seamusrobertmurphy/VM0048/issues
          - text: Repo Collection
            href: https://github.com/seamusrobertmurphy/
      - icon: linkedin
        href: https://linkedin.com/in/seamusrobertmurphy
      
  sidebar:
      pinned: true
      style: "docked"
      collapse-level: 1
      contents:
      - text: "Home"
        href: index.qmd
      - text: "Baseline"
        href: baseline.qmd
      - text: "Risk"
        href: deforisk.qmd
      - text: "Leakage"
        href: leakage.qmd
      - section: "About"
        contents:
          - text: "Resume"
            href: about.qmd
          - text: "Teaching"
            href: teaching/index.qmd

format:
  html:
    theme: [cosmo, styles.scss]
engine: knitr
